### PR TITLE
132 move host config opts

### PR DESCRIPTION
**Pull request by emirotin**
This implements the changes as mentioned by Kostas here: https://github.com/resin-io/resin-cli/issues/534#issuecomment-317395447

I've carefully checked the corresponding docker API docs and the confirm these are the needed changes.
I'm only surprised by the fact the `Volumes` key used to work with docker 1.10 as according to the docs the Volumes is not part of the HostConfig, and instead is the top-level setting: https://docs.docker.com/engine/api/v1.22/#21-containers, while the start endpoint did transform the accepted body into the HostConfig settings.

Anyways, I've put this key as the top-level option as expected.

I've made some additional changes:
* updated some dev dependencies as the old versions didn't work with my node v8
* removed the readme handlebars template as it looks it wasn't used and the readme is static now
* rebuilt the docs (lots of changes seem to be not reflected there)
* updated couple of resin dependencies

### CODE REVIEW

**Comment by emirotin** [comment]
The tests are failing on Node < 6 because of some ES6 syntax (specifically: default params) in the drivelist dependency.

So I'm going to drop support for Node < 6 here as we've done in the CLI already

**Review by pimterry — APPROVED** [review]
Code all looks great to me. Have you tested it against all the versions of Docker we care about from https://github.com/resin-io/resin-cli/issues/534#issuecomment-317409857? As long as you're sure this works with each those, this looks good to me.

**Comment by emirotin** [comment]
Didn't test yet, only implemented according to the docs, will create a branch in the CLI with this version of sync and test that before merging.

**Review by lekkas — APPROVED** [review]

**Comment by emirotin** [comment]
Tested by Shaun, merging

**Pull request merged**
